import type { Metadata } from "next";
import { ClerkProvider} from "@clerk/nextjs";
import "./globals.css";


export const metadata: Metadata = {
  title: "Ardhi App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
